<?php

return array (
  'name' => 'TpMeCMS',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.3',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'user' => '会员配置',
    'example' => '示例分组',
    'tpmecms' => 'TpMeCMS',
    'weixin' => '微信设置',
    'alipay' => '支付宝设置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'attachmentcategory' => 
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'app_id' => 'wx4966310850000000',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  'mch_id' => '1618630644',
  'key' => 'wuximeisujingkejikeluboshixihu88',
  'wx_app_id' => 'wxa637a21e57e20ada',
  'wx_secret' => '7ba39f3b593d55db3d158ec50e40e39e',
  'tel' => '19999999999',
  'index_url' => '/cms/index/index',
  'wxqr_img' => '/uploads/20210622/a572d67db33e94f6dc8dd2e908c03ff2.jpg',
  'addr' => '无锡市惠山区宇野网络大厦',
  'addr2' => 'B1108',
  'email' => '496631085@qq.com',
  'banquan' => 'TpMeCms © 2021 版权所有',
  'technical_support' => '技术支持：TpMeCMS',
  'route_switch' => '1',
  'wechat_cert_path' => '/uploads/apiclient_cert.pem',
  'wechat_key_path' => '/uploads/apiclient_key.pem',
  'ali_app_id' => '2021003125655437',
  'ali_apiDomain' => 'https://openapi.alipay.com/gateway.do',
);
